<a href="https://colab.research.google.com/github/darshank26/Learn-NumPy/blob/main/Learn_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Welcome to NumPy!***

* NumPy is a Python library used for numerical computing and data manipulation.

* It provides a special type of array called ndarray to store and operate on large sets of numerical data efficiently.

* NumPy's arrays are faster than regular Python lists because they are implemented in a low-level language.

* You can perform various operations on NumPy arrays, such as mathematical calculations, sorting, and selecting specific elements.

* NumPy supports broadcasting, which allows you to perform operations between arrays of different shapes without loops.

* It is widely used in scientific computing and data analysis, and it serves as the foundation for other popular libraries like SciPy, Pandas, and Matplotlib.

# **Installing NumPy**

In [ ]:
#conda install numpy

#or

#pip install numpy

# **How to import NumPy**

In [ ]:
import numpy as np

# Difference between a Python list and a NumPy array

<table>
  <tr>
    <th></th>
    <th><b>Python Lists</b></th>
    <th><b>NumPy Arrays</b></th>
  </tr>
  <tr>
    <td><b>Data Type</b></td>
    <td>Can store elements of different data types together</td>
    <td>Homogeneous, can only contain elements of the same data type</td>
  </tr>
  <tr>
    <td><b>Memory Efficiency</b></td>
    <td>Higher memory overhead due to storing type information and metadata for each element</td>
    <td>More memory-efficient, stores only the raw data</td>
  </tr>
  <tr>
    <td><b>Performance</b></td>
    <td>Slower for numerical operations, involves interpretation and dynamic dispatch</td>
    <td>Faster for numerical operations, utilizes optimized C code</td>
  </tr>
  <tr>
    <td><b>Array Operations</b></td>
    <td>Lack built-in array operations, requiring manual iteration or external libraries</td>
    <td>Offers a wide range of optimized array operations and functions</td>
  </tr>
  <tr>
    <td><b>Broadcasting</b></td>
    <td>Does not support broadcasting, element-wise operations often require explicit loops</td>
    <td>Supports broadcasting, simplifying operations between arrays of different shapes</td>
  </tr>
</table>


# Why is NumPy Faster Than Lists?



<p>NumPy is faster than Python lists due to the following reasons:</p>

<ol>
  <li><strong>Data Organization:</strong> NumPy arrays store data in a way that allows for faster calculations. Python lists can hold different types of data, which slows down computations.</li>
  <li><strong>Memory Usage:</strong> NumPy arrays use memory more efficiently by storing data in a contiguous block, making it faster to access elements. Python lists have scattered memory locations, leading to slower access times.</li>
  <li><strong>Optimized Operations:</strong> NumPy is built with highly optimized code that performs calculations faster than Python's built-in operations for lists.</li>
  <li><strong>Bulk Operations:</strong> NumPy can perform calculations on entire arrays at once, without the need for explicit loops. This saves time compared to iterating over elements in Python lists.</li>
  <li><strong>Integration with Libraries:</strong> NumPy is widely used in scientific computing libraries, which are designed to work seamlessly with NumPy. This integration further boosts performance.</li>
</ol>

<p>In summary, NumPy's speed advantage comes from its efficient data organization, optimized calculations, bulk operations, and integration with specialized libraries. These factors make NumPy faster than Python lists for numerical computations.</p>


# NumPy Creating Arrays


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print(arr)

print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Dimensions in Arrays


A dimension in arrays is one level of array depth


#0-D Arrays


Each value in an array is O-D Array



In [ ]:
import numpy as np

arr = np.array(1);

print(arr)

print("Dimension of Array : ", arr.ndim)

1
Dimension of Array 0


#1-D Array

An array that has a 0-D Array as its elements is called uni-dimensional or 1-D Array


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print(arr)

print("Dimension of Array :", arr.ndim)

[1 2 3 4 5 6]
Dimension of Array : 1


#2-D Array

An array that has a 1-D Array as its elements is called 2-D Array


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]]);

print(arr)

print("Dimension of Array :", arr.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
Dimension of Array : 2


#3-D Array


An array that has a 2-D Array as its elements is called  2-D Array

In [ ]:
import numpy as np

arr = np.array([[[1,2,3,4,5,6], [1,0,1,0,1,0]], [[7,8,9,10,11,12],[2,0,2,0,2,0]], [[13,14,15,16,17,18],[3,0,3,0,3,0]]]);

print(arr)

print("Dimension of Array :", arr.ndim)

[[[ 1  2  3  4  5  6]
  [ 1  0  1  0  1  0]]

 [[ 7  8  9 10 11 12]
  [ 2  0  2  0  2  0]]

 [[13 14 15 16 17 18]
  [ 3  0  3  0  3  0]]]
Dimension of Array : 3


#4-D Array

An array that has a 3-D Array as its elements is called 4-D Array

In [ ]:
import numpy as np

arr = np.array([[[[1,2,3,4,5,6], [1,0,1,0,1,0]]], [[[7,8,9,10,11,12],[2,0,2,0,2,0]]], [[[13,14,15,16,17,18],[3,0,3,0,3,0]]]]);

print(arr)

print("Dimension of Array :", arr.ndim)

[[[[ 1  2  3  4  5  6]
   [ 1  0  1  0  1  0]]]


 [[[ 7  8  9 10 11 12]
   [ 2  0  2  0  2  0]]]


 [[[13 14 15 16 17 18]
   [ 3  0  3  0  3  0]]]]
Dimension of Array : 4


#Higher Dimensional Arrays


An array can have any number of dimensional, so when array is created you can specify the dimensions for it

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6], ndmin=6);

print(arr)
print("Dimension of Array :", arr.ndim)

[[[[[[1 2 3 4 5 6]]]]]]
Dimension of Array : 6


#Array Indexing

An array indexing is accessing array elements in any given numpy array.

The index in numpy array starts from 0, this means first element has index  0 and second element has index 1 and so on

You can access array elements using this index position


**Accessing Array elements from 1-D Array**

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print(arr[1])


2


**Accessing Array elements from 2-D Array**

To access array elements from 2-D array we use comma seperated integers representing dimension and index of the elements

Consider 2-D array as table where rows represent dimensions and column represents

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]]);

print(arr[1,4])


11


**Accessing Array elements from 3-D Array**

To access array elements from 3-D array we use comma seperated integers representing dimension and index of the elements

In [ ]:
import numpy as np

arr = np.array([ [[1,2,3], [7,8,9]] , [[10,11,12], [13,14,15]] , [[16,17,18], [19,20,21]]]);

print(arr[1,0,2])

12


**Accessing Array elements from 4-D Array**

To access array elements from 4-D array we use comma seperated integers representing dimension and index of the elements

In [ ]:
import numpy as np

arr = np.array([[ [[1,2,3], [7,8,9]] ], [[[10,11,12], [13,14,15]] ], [[[16,17,18], [19,20,21]]]]);

print(arr[1,0,1,1])

14


#Negative Indexing

We can access array elements of any given numpy array using negative index

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]]);

print(arr[1,-1])

12


#NumPy Array Slicing

Slicing in python means making taking an elements from one given index to another given index


For slicing any given numpy array we pass `[ start : end ]`

We can also pass step like, `[ start : end : step ]`

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print("Array first slice from index 1 to 5 : ",arr[1:5])


arr2 = np.array([12,23,36,44,57,63]);

print("Array second slice from index 1 to last : ",arr2[1:])

arr3 = np.array([53,43,35,24,4,89]);

print("Array third slice from  start to index 4 : ",arr3[:4])




Array first slice from index 1 to 5 :  [2 3 4 5]
Array second slice from index 1 to last :  [23 36 44 57 63]
Array third slice from  start to index 4 :  [53 43 35 24]


#Negative Slicing

In negative slicing we can use minus operator to refer an index from end

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print("Array first negative slice from index -3 to -2 : ",arr[-3:-1])

arr2 = np.array([12,23,36,44,57,63]);

print("Array second negative slice from index -4 to last : ",arr2[-4:])

arr3 = np.array([53,43,35,24,4,89]);

print("Array third  negative slice from  start to -3 : ",arr3[:-3])


Array first negative slice from index -3 to -2 :  [4 5]
Array second negative slice from index -4 to last :  [36 44 57 63]
Array third  negative slice from  start to -3 :  [53 43 35]


#Step

We can use a step value to determine the step while slicing any numpy array

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10]);

print("Step of 2, from index 1 to index 8: ",arr[1:8:2])

print("Step of 3, from start to index 6 : ",arr[:6:3])

print("Step of 2, from start to last : ",arr[::2])

print("Step of 3 : ",arr[1::2])


Step of 2 :  [2 4 6 8]
Step of 3 :  [1 4]
Step of 2 :  [1 3 5 7 9]
Step of 3 :  [ 2  4  6  8 10]


#Slicing 2-D array

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]);

print("Slicing 2-D Array : ",arr[1,1:4])


Slicing 2-D Array :  [ 8  9 10]


#Slicing 3-D Array

In [ ]:
import numpy as np

arr = np.array([ [[1,2,3,4,5,6],[7,8,9,10,11,12]], [[11,12,13,14,15,16],[17,18,19,20,21,22]] ]);

print("Slicing 2-D Array : ",arr[0,1,1:4])


Slicing 2-D Array :  [ 8  9 10]


#Data Type in Pyton

In python we have following data types such as,

```
1. strings - eg. "A","ABC"
2. integer - eg. 1,2,3,4,-5
3. float  - eg. 1.0,2.0,-3.43
4. boolean - eg. true,false
5. complex - eg. 1.0 + 2.0j, 3.0 + 10j
```








#Data Type in Numpy Array

In NumPy we have more data type, which is represented usinf single characters such as,

```
i - integer
f - float
b - boolean
c - complex float
u - unsigned integer
m - timedelta
M - datetime
O - object
S - strings
U - unicode string
V - void
```

#Checking the Data type of NumPy Array




we can check data type of given array using ```dtype```

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5]);

print(arr.dtype);

arr2 = np.array(["A","B","C"]);

print(arr2.dtype);

arr3 = np.array([1.2,2.3,4.9]);

print(arr3.dtype);

arr4 = np.array([1.2 + 2.0j,2.3+4.2j,4.9+5.6j]);

print(arr4.dtype);

arr4 = np.array([1.2 + 2.0j,2.3+4.2j,4.9+5.6j]);

print(arr4.dtype);


int64
<U1
float64
complex128


#Changing the Data Type of existing Array




The best way to change the datatype of any numpy array is to make a copy of of the array using ```astype()``` method

The ```astype()``` method create the copy of the array, and also allow you to specify the data type as the parameter

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5]);

new_arr = arr.astype('S');

print(new_arr.dtype);

print(new_arr);


new_arr_1 = arr.astype('f');

print(new_arr_1.dtype);

print(new_arr_1);


|S21
[b'1' b'2' b'3' b'4' b'5']
float32
[1. 2. 3. 4. 5.]


#NumpyPy Array Copy and View

**Copy**

* A copy is a new array that owns its data.
* Changes made to the copy do not affect the original array.
* Changes made to the original array do not affect the copy.

**View:**

* A view is just a view of the original array.
* It does not own the data; it provides a different  
* perspective on the original array.
* Changes made to the view will affect the original array, and vice versa.

In [10]:
#Copy Example

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
copy_array = arr.copy()
arr[3] = 100

print(arr)
print(copy_array)

[  1   2   3 100   5]
[1 2 3 4 5]


In [9]:
#View Example

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
view_array = arr.view()
arr[1] = 100

print(arr)
print(view_array)

[  1 100   3   4   5]
[  1 100   3   4   5]


#NumPy Array Shape


The shape of array is number of elements in each dimensions

Numpy Array has the attibute called ```shape``` to return the tupe corresponding the mumber of elements in each dimension

In [15]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)

arr2 = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])

print(arr2.shape)

arr3 = np.array([[[1, 2, 3, 4, 5],[6,7,8,9,10]],[[1, 2, 3, 4, 5],[6,7,8,9,10]]])

print(arr3.shape)


(5,)
(2, 5)
(2, 2, 5)


#Reshaping the Array

Reshaping means changing the shape of the array, where shape means numbers of the elements in each dimension, through reshaping we can add or change the shape of array

#chaging 1-D array to 2-D array

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("Old Array dimensions : ",arr.ndim)

new_arr = arr.reshape(2,3)

print("Reshape Array :\n", new_arr)

print("New Array dimensions :",new_arr.ndim)

Old Array dimensions :  1
Reshape Array :
 [[1 2 3]
 [4 5 6]]
New Array dimensions : 2


##chaging 1-D array to 3-D array

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("Old Array dimensions : ",arr.ndim)

new_arr = arr.reshape(1,3,2)

print("Reshape Array :\n", new_arr)

print("New Array dimensions :",new_arr.ndim)

Old Array dimensions :  1
Reshape Array :
 [[[1 2]
  [3 4]
  [5 6]]]
New Array dimensions : 3


##chaging 1-D array to 2-D array

In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("Old Array dimensions : ",arr.ndim)

new_arr = arr.reshape(1,1,2,3)

print("Reshape Array :\n", new_arr)

print("New Array dimensions :",new_arr.ndim)

Old Array dimensions :  1
Reshape Array :
 [[[[1 2 3]
   [4 5 6]]]]
New Array dimensions : 4


#chaging 2-D array to 3-D array

In [50]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])

print("Old Array dimensions : ",arr.ndim)

new_arr = arr.reshape(2,3,2)

print("Reshape Array :\n", new_arr)

print("New Array dimensions :",new_arr.ndim)

Old Array dimensions :  2
Reshape Array :
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
New Array dimensions : 3


#Unknown Dimension

You can have one unknown dimension, this means you do not have to specify the exact number of one dimension in the reshape method

In [59]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])

print("Old Array : \n",arr)
print("Old Array Dimension: ",arr.ndim)

print("UnKnow Dimension array : \n",arr.reshape(2,2,-1))
print("UnKnow Dimension  array's Dimension: ",arr.ndim)

Old Array : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Old Array Dimension:  2
UnKnow Dimension array : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
UnKnow Dimension  array's Dimension:  2


#Flatting the array

Flatting the array means converting mutidimensional array to 1-D array

In [55]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])

print("Old Array : \n",arr)
print("Old Array Dimension: ",arr.ndim)

print("Flatting array : ",arr.reshape(-1))
print("Flatting array Dimension : ",arr.ndim)

Old Array : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Old Array Dimension:  2
Flatting array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Flatting array Dimension :  2


#Iterating through NumPy Array

You can iterate any give numpy array using for loop

#Iterating 1D Array

In [60]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

for i in arr:
  print(i);

1
2
3
4
5
6
7


#Iterating 2D Array

In [64]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],[8,9,10,11,12]])

for i in arr:
  print(i);


# Iterating through each elements of 2D array
arr = np.array([[1,2,3,4,5,6],[8,9,10,11,12]])

for i in arr:
  for j in i:
    print(j)

[1, 2, 3, 4, 5, 6]
[8, 9, 10, 11, 12]
1
2
3
4
5
6
8
9
10
11
12


<ipython-input-64-d641afdc2f7e>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4,5,6],[8,9,10,11,12]])
<ipython-input-64-d641afdc2f7e>:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4,5,6],[8,9,10,11,12]])


#Iterating through 3D array

In [65]:
import numpy as np

arr = np.array([[[1,2,3,4,5,6],[8,9,10,11,12]],[[1,2,3,4,5,6],[8,9,10,11,12]]])

for i in arr:
  print(i);


# Iterating through each elements of 3D array
arr = np.array([[[1,2,3,4,5,6],[8,9,10,11,12]],[[1,2,3,4,5,6],[8,9,10,11,12]]])

for i in arr:
  for j in i:
    for k in j:
          print(k)

[list([1, 2, 3, 4, 5, 6]) list([8, 9, 10, 11, 12])]
[list([1, 2, 3, 4, 5, 6]) list([8, 9, 10, 11, 12])]
1
2
3
4
5
6
8
9
10
11
12
1
2
3
4
5
6
8
9
10
11
12


<ipython-input-65-5bf95638f4fa>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1,2,3,4,5,6],[8,9,10,11,12]],[[1,2,3,4,5,6],[8,9,10,11,12]]])
<ipython-input-65-5bf95638f4fa>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1,2,3,4,5,6],[8,9,10,11,12]],[[1,2,3,4,5,6],[8,9,10,11,12]]])


#Iterating NumPy array through nditer()

```nditer``` function is use to iterate from basic dimensions to higher dimensions

As you can see in above example of iterating array we have used ```for``` loop to iterate through higher dimensions array which can be tedious and difficult to write code for higher dimension, so ```nditer`` solves your problem for it.


In [84]:
import numpy as np

# Iterating through each elements of 3D array
arr = np.array([1,2,3,4,5,6])

for i in np.nditer(arr):
  print(i);

1
2
3
4
5
6


#Iterating through diffferent data type

* To change the data type of elements while iterating in NumPy, use the ```op_dtypes``` argument.

* NumPy doesn't modify the data type in-place; it requires a buffer for the conversion.

* Enable the buffer by passing ```flags=['buffered']``` to ```nditer()```.

* The buffer allows NumPy to allocate space for the data type conversion during iteration.

In [101]:
import numpy as np

arr = np.array([[1.0, 2.0, 3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1.0'
b'2.0'
b'3.0'
b'4.0'
b'5.0'
b'6.0'
b'7.0'
b'8.0'
b'9.0'


#Iterating through step

In [118]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


#Joining the Array

You can join two different array using ```concatenate``` function

In [124]:
import numpy as np

arr = np.array([1, 2, 3, 4])

arr2 = np.array([11, 12, 13, 14])

print(np.concatenate((arr,arr2)))

[ 1  2  3  4 11 12 13 14]


Join 2-D array using axis = 1

In [126]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr2 = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])

print(np.concatenate((arr,arr2),axis = 1))

[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]]


#Joing array using stack function

* Stacking and concatenation are similar, but stacking adds a new axis.
* Stacking places arrays on top of each other.
* We can stack 1-D arrays by concatenating them along the second axis.
* To stack arrays, use the ```stack()``` method and provide the arrays to join.
*If no axis is specified, it defaults to 0.

In [131]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr2 = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])

print(np.stack((arr,arr2),axis = 2))

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]]]


#Stacking along the row

You can stack two different array using ```hstack``` function

In [135]:
arr = np.array([1, 2, 3, 4])

arr2 = np.array([11, 12, 13, 14])

print(np.hstack((arr,arr2)))

[ 1  2  3  4 11 12 13 14]


#Stacking along the column

You can stack two different array using ```vstack``` function

In [136]:
arr = np.array([1, 2, 3, 4])

arr2 = np.array([11, 12, 13, 14])

print(np.vstack((arr,arr2)))

[[ 1  2  3  4]
 [11 12 13 14]]


#Stacking Along Height (depth)

You can stack two different array using ```dstack``` function

In [137]:
arr = np.array([1, 2, 3, 4])

arr2 = np.array([11, 12, 13, 14])

print(np.dstack((arr,arr2)))

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]]
