<a href="https://colab.research.google.com/github/darshank26/Learn-NumPy/blob/main/Learn_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Welcome to NumPy!***

* NumPy is a Python library used for numerical computing and data manipulation.

* It provides a special type of array called ndarray to store and operate on large sets of numerical data efficiently.

* NumPy's arrays are faster than regular Python lists because they are implemented in a low-level language.

* You can perform various operations on NumPy arrays, such as mathematical calculations, sorting, and selecting specific elements.

* NumPy supports broadcasting, which allows you to perform operations between arrays of different shapes without loops.

* It is widely used in scientific computing and data analysis, and it serves as the foundation for other popular libraries like SciPy, Pandas, and Matplotlib.

# **Installing NumPy**

In [ ]:
#conda install numpy

#or

#pip install numpy

# **How to import NumPy**

In [ ]:
import numpy as np

# Difference between a Python list and a NumPy array

<table>
  <tr>
    <th></th>
    <th><b>Python Lists</b></th>
    <th><b>NumPy Arrays</b></th>
  </tr>
  <tr>
    <td><b>Data Type</b></td>
    <td>Can store elements of different data types together</td>
    <td>Homogeneous, can only contain elements of the same data type</td>
  </tr>
  <tr>
    <td><b>Memory Efficiency</b></td>
    <td>Higher memory overhead due to storing type information and metadata for each element</td>
    <td>More memory-efficient, stores only the raw data</td>
  </tr>
  <tr>
    <td><b>Performance</b></td>
    <td>Slower for numerical operations, involves interpretation and dynamic dispatch</td>
    <td>Faster for numerical operations, utilizes optimized C code</td>
  </tr>
  <tr>
    <td><b>Array Operations</b></td>
    <td>Lack built-in array operations, requiring manual iteration or external libraries</td>
    <td>Offers a wide range of optimized array operations and functions</td>
  </tr>
  <tr>
    <td><b>Broadcasting</b></td>
    <td>Does not support broadcasting, element-wise operations often require explicit loops</td>
    <td>Supports broadcasting, simplifying operations between arrays of different shapes</td>
  </tr>
</table>


# Why is NumPy Faster Than Lists?



<p>NumPy is faster than Python lists due to the following reasons:</p>

<ol>
  <li><strong>Data Organization:</strong> NumPy arrays store data in a way that allows for faster calculations. Python lists can hold different types of data, which slows down computations.</li>
  <li><strong>Memory Usage:</strong> NumPy arrays use memory more efficiently by storing data in a contiguous block, making it faster to access elements. Python lists have scattered memory locations, leading to slower access times.</li>
  <li><strong>Optimized Operations:</strong> NumPy is built with highly optimized code that performs calculations faster than Python's built-in operations for lists.</li>
  <li><strong>Bulk Operations:</strong> NumPy can perform calculations on entire arrays at once, without the need for explicit loops. This saves time compared to iterating over elements in Python lists.</li>
  <li><strong>Integration with Libraries:</strong> NumPy is widely used in scientific computing libraries, which are designed to work seamlessly with NumPy. This integration further boosts performance.</li>
</ol>

<p>In summary, NumPy's speed advantage comes from its efficient data organization, optimized calculations, bulk operations, and integration with specialized libraries. These factors make NumPy faster than Python lists for numerical computations.</p>


# NumPy Creating Arrays


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print(arr)

print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Dimensions in Arrays


A dimension in arrays is one level of array depth


#0-D Arrays


Each value in an array is O-D Array



In [ ]:
import numpy as np

arr = np.array(1);

print(arr)

print("Dimension of Array : ", arr.ndim)

1
Dimension of Array 0


#1-D Array

An array that has a 0-D Array as its elements is called uni-dimensional or 1-D Array


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print(arr)

print("Dimension of Array :", arr.ndim)

[1 2 3 4 5 6]
Dimension of Array : 1


#2-D Array

An array that has a 1-D Array as its elements is called 2-D Array


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]]);

print(arr)

print("Dimension of Array :", arr.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
Dimension of Array : 2


#3-D Array


An array that has a 2-D Array as its elements is called  2-D Array

In [ ]:
import numpy as np

arr = np.array([[[1,2,3,4,5,6], [1,0,1,0,1,0]], [[7,8,9,10,11,12],[2,0,2,0,2,0]], [[13,14,15,16,17,18],[3,0,3,0,3,0]]]);

print(arr)

print("Dimension of Array :", arr.ndim)

[[[ 1  2  3  4  5  6]
  [ 1  0  1  0  1  0]]

 [[ 7  8  9 10 11 12]
  [ 2  0  2  0  2  0]]

 [[13 14 15 16 17 18]
  [ 3  0  3  0  3  0]]]
Dimension of Array : 3


#4-D Array

An array that has a 3-D Array as its elements is called 4-D Array

In [ ]:
import numpy as np

arr = np.array([[[[1,2,3,4,5,6], [1,0,1,0,1,0]]], [[[7,8,9,10,11,12],[2,0,2,0,2,0]]], [[[13,14,15,16,17,18],[3,0,3,0,3,0]]]]);

print(arr)

print("Dimension of Array :", arr.ndim)

[[[[ 1  2  3  4  5  6]
   [ 1  0  1  0  1  0]]]


 [[[ 7  8  9 10 11 12]
   [ 2  0  2  0  2  0]]]


 [[[13 14 15 16 17 18]
   [ 3  0  3  0  3  0]]]]
Dimension of Array : 4


#Higher Dimensional Arrays


An array can have any number of dimensional, so when array is created you can specify the dimensions for it

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6], ndmin=6);

print(arr)
print("Dimension of Array :", arr.ndim)

[[[[[[1 2 3 4 5 6]]]]]]
Dimension of Array : 6


#Array Indexing

An array indexing is accessing array elements in any given numpy array.

The index in numpy array starts from 0, this means first element has index  0 and second element has index 1 and so on

You can access array elements using this index position


**Accessing Array elements from 1-D Array**

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print(arr[1])


2


**Accessing Array elements from 2-D Array**

To access array elements from 2-D array we use comma seperated integers representing dimension and index of the elements

Consider 2-D array as table where rows represent dimensions and column represents

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]]);

print(arr[1,4])


11


**Accessing Array elements from 3-D Array**

To access array elements from 3-D array we use comma seperated integers representing dimension and index of the elements

In [ ]:
import numpy as np

arr = np.array([ [[1,2,3], [7,8,9]] , [[10,11,12], [13,14,15]] , [[16,17,18], [19,20,21]]]);

print(arr[1,0,2])

12


**Accessing Array elements from 4-D Array**

To access array elements from 4-D array we use comma seperated integers representing dimension and index of the elements

In [ ]:
import numpy as np

arr = np.array([[ [[1,2,3], [7,8,9]] ], [[[10,11,12], [13,14,15]] ], [[[16,17,18], [19,20,21]]]]);

print(arr[1,0,1,1])

14


#Negative Indexing

We can access array elements of any given numpy array using negative index

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]]);

print(arr[1,-1])

12


#NumPy Array Slicing

Slicing in python means making taking an elements from one given index to another given index


For slicing any given numpy array we pass `[ start : end ]`

We can also pass step like, `[ start : end : step ]`

In [10]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print("Array first slice from index 1 to 5 : ",arr[1:5])


arr2 = np.array([12,23,36,44,57,63]);

print("Array second slice from index 1 to last : ",arr2[1:])

arr3 = np.array([53,43,35,24,4,89]);

print("Array third slice from  start to index 4 : ",arr3[:4])




Array first slice from index 1 to 5 :  [2 3 4 5]
Array second slice from index 1 to last :  [23 36 44 57 63]
Array third slice from  start to index 4 :  [53 43 35 24]


#Negative Slicing

In negative slicing we can use minus operator to refer an index from end

In [21]:
import numpy as np

arr = np.array([1,2,3,4,5,6]);

print("Array first negative slice from index -3 to -2 : ",arr[-3:-1])

arr2 = np.array([12,23,36,44,57,63]);

print("Array second negative slice from index -4 to last : ",arr2[-4:])

arr3 = np.array([53,43,35,24,4,89]);

print("Array third  negative slice from  start to -3 : ",arr3[:-3])


Array first negative slice from index -3 to -2 :  [4 5]
Array second negative slice from index -4 to last :  [36 44 57 63]
Array third  negative slice from  start to -3 :  [53 43 35]


#Step

We can use a step value to determine the step while slicing any numpy array

In [27]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10]);

print("Step of 2, from index 1 to index 8: ",arr[1:8:2])

print("Step of 3, from start to index 6 : ",arr[:6:3])

print("Step of 2, from start to last : ",arr[::2])

print("Step of 3 : ",arr[1::2])


Step of 2 :  [2 4 6 8]
Step of 3 :  [1 4]
Step of 2 :  [1 3 5 7 9]
Step of 3 :  [ 2  4  6  8 10]


#Slicing 2-D array

In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]);

print("Slicing 2-D Array : ",arr[1,1:4])


Slicing 2-D Array :  [ 8  9 10]


#Slicing 3-D Array

In [32]:
import numpy as np

arr = np.array([ [[1,2,3,4,5,6],[7,8,9,10,11,12]], [[11,12,13,14,15,16],[17,18,19,20,21,22]] ]);

print("Slicing 2-D Array : ",arr[0,1,1:4])


Slicing 2-D Array :  [ 8  9 10]


#Data Type in Pyton

In python we have following data types such as,

```
1. strings - eg. "A","ABC"
2. integer - eg. 1,2,3,4,-5
3. float  - eg. 1.0,2.0,-3.43
4. boolean - eg. true,false
5. complex - eg. 1.0 + 2.0j, 3.0 + 10j
```








#Data Type in Numpy Array

In NumPy we have more data type, which is represented usinf single characters such as,

```
i - integer
f - float
b - boolean
c - complex float
u - unsigned integer
m - timedelta
M - datetime
O - object
S - strings
U - unicode string
V - void
```

#Checking the Data type of NumPy Array

we can check data type of given array using ```dtype```

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5]);

print(arr.dtype);

arr2 = np.array(["A","B","C"]);

print(arr2.dtype);

arr3 = np.array([1.2,2.3,4.9]);

print(arr3.dtype);

arr4 = np.array([1.2 + 2.0j,2.3+4.2j,4.9+5.6j]);

print(arr4.dtype);

arr4 = np.array([1.2 + 2.0j,2.3+4.2j,4.9+5.6j]);

print(arr4.dtype);


int64
<U1
float64
complex128
